server:
  # 端口
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    # 配置请求编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: spring-security-demo
  lifecycle:
    # 设置缓冲期，最大等待时间
    timeout-per-shutdown-phase: 30s
  main:
    allow-bean-definition-overriding: false
  servlet:
    multipart:
      # 允许多文件上传
      enabled: true
      # 上传单个文件的最大值
      max-file-size: 10MB
      # 上传的总文件最大值
      max-request-size: 100MB
  ############################################## 配置mysql数据源 ################################################
  datasource:
    # 数据库驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone=GMT%2B8 (北京时间 == 东八区时间) 之前UTC 差了8小时 （暂改为东8）
    url: jdbc:mysql://192.168.204.151:3306/security?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # 数据库连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 5
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 30
      # 控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 连接池名称
      pool-name: MyHikariCP
      # connection在连接池中的存活时间默认30分钟
      max-lifetime: 1800000
      # 等待来自池的连接的最大毫秒数,默认 30000
      connection-timeout: 30000
  ########################################### Redis相关配置 #######################################################
  redis:
    # redis服务器地址
    host: 192.168.204.151
    # redis服务器连接端口
    port: 6379
    # redis默认有16个分片，默认使用0号分片
    database: 0
    # 连接超时时间（毫秒）
    connect-timeout: 2000
    # redis密码
    password: 123456
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大连接数（使用负值表示没有限制
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: 3000
###################################### mybatis-plus 相关配置 ##########################################################
mybatis-plus:
  # xml扫描路径， 表示Mapper文件存放的位置，当Mapper文件跟对应的Mapper接口处于同一位置的时候可以不用指定该属性的值
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体类扫描路径， 多个package用逗号或者分号分隔
  type-aliases-package: com.george.**.entity
  global-config:
    # 是否开启 LOGO
    banner: true
    db-config:
      # 主键类型 自增
      id-type: auto
      # 表名、是否使用下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # 原生配置
  configuration:
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    # 使全局的映射器启用或禁用缓存。
    cache-enabled: true
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazy-loading-enabled: false
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multiple-result-sets-enabled: true
########################################## logback日志配置 #####################################################
logging:
  # 使用的logback文件
  config: classpath:logback/logback-spring.xml
########################################## actuator服务监控 ##############################################
management:
  endpoint:
    # 允许actuator关机
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"